name: PR Workflow

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, this PR workflow is running!"
